name: molsim
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=1.2.4
  - numpy-base=1.17.4
  - pandas=0.25.3
  - pip=19.3.1
  - plotly=4.4.1
  - python=3.7.5
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - pip:
    - hyperopt==0.2.2
    - pandas-profiling==2.3.0

