name: molsim
channels:
  - plotly
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.0
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bokeh=1.4.0
  - ca-certificates=2019.11.27
  - certifi=2019.11.28
  - cycler=0.10.0
  - decorator=4.4.1
  - defusedxml=0.6.0
  - entrypoints=0.3
  - freetype=2.10.0
  - holoviews=1.12.7
  - importlib_metadata=1.3.0
  - intel-openmp=2019.4
  - ipykernel=5.1.3
  - ipython=7.11.1
  - ipython_genutils=0.2.0
  - jedi=0.15.2
  - jinja2=2.10.3
  - joblib=0.14.1
  - jpeg=9c
  - json5=0.8.5
  - jsonschema=3.2.0
  - jupyter_client=5.3.3
  - jupyter_core=4.6.1
  - jupyterlab=1.2.4
  - jupyterlab_server=1.0.6
  - kiwisolver=1.1.0
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgfortran=3.0.1
  - libpng=1.6.37
  - libsodium=1.0.17
  - libtiff=4.0.10
  - llvm-openmp=9.0.1
  - lz4-c=1.8.3
  - markupsafe=1.1.1
  - matplotlib-base=2.2.4
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.0.2
  - nb_conda=2.2.1
  - nb_conda_kernels=2.2.2
  - nbconvert=5.6.1
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.17.4
  - numpy-base=1.17.4
  - olefile=0.46
  - openssl=1.1.1d
  - packaging=19.2
  - pandas=0.25.3
  - pandoc=2.9.1
  - param=1.9.2
  - parso=0.5.2
  - patsy=0.5.1
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.1
  - pip=19.3.1
  - plotly=4.4.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.2
  - ptyprocess=0.6.0
  - pygments=2.5.2
  - pyparsing=2.4.6
  - pyrsistent=0.15.6
  - python=3.7.5
  - python-dateutil=2.8.1
  - pytz=2019.3
  - pyviz_comms=0.7.2
  - readline=7.0
  - retrying=1.3.3
  - scikit-learn=0.21.3
  - scipy=1.3.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=42.0.2
  - six=1.13.0
  - sqlite=3.30.1
  - statsmodels=0.10.1
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.3
  - wcwidth=0.1.8
  - wheel=0.33.6
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.4.0
  - pip:
    - astroid==2.3.3
    - astropy==4.0
    - cloudpickle==1.2.2
    - confuse==1.0.0
    - future==0.18.2
    - htmlmin==0.1.12
    - hyperopt==0.2.2
    - ipython-genutils==0.2.0
    - isort==4.3.21
    - jupyter-client==5.3.4
    - jupyterthemes==0.20.0
    - lazy-object-proxy==1.4.3
    - lesscpy==0.13.0
    - llvmlite==0.31.0
    - matplotlib==3.1.2
    - mccabe==0.6.1
    - missingno==0.4.2
    - nbformat==4.4.0
    - networkx==2.2
    - numba==0.47.0
    - pandas-profiling==2.3.0
    - pandocfilters==1.4.2
    - phik==0.9.8
    - pluggy==0.13.1
    - ply==3.11
    - py==1.8.1
    - pylint==2.4.4
    - pytest==5.3.2
    - pytest-pylint==0.14.1
    - pyyaml==5.2
    - pyzmq==18.1.1
    - tqdm==4.41.1
    - typed-ast==1.4.0
    - webencodings==0.5.1
    - wrapt==1.11.2

