name: Python package

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  test_conda:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']
        python-version: ['3.7']
    steps:
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash -l {0}
        run:  conda env create --name molsim_ml --file=environment.yml -y && conda activate molsim_ml && python test/test.py
      - name: Conda list
        shell: pwsh
        run:  conda env create --name molsim_ml --file=environment.yml -y && conda activate molsim_ml && python test/test.py
